name: amicana_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos de iOS
  cupertino_icons: ^1.0.8

  # Para usar fuentes de Google de forma sencilla
  google_fonts: ^6.2.1 # <--- DEPENDENCIA AÑADIDA

  # Para manejo de estado (puedes eliminar el que no uses)
  flutter_bloc: ^8.1.5
  provider: ^6.1.2

  # Para peticiones HTTP a tu backend
  http: ^1.2.1
  dio: ^5.4.3

  # Para navegación
  go_router: ^14.1.0

  # Para guardar datos simples en el dispositivo
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Contiene un set de reglas para fomentar buenas prácticas de código
  flutter_lints: ^3.0.0

# La siguiente sección es específica para Flutter.
flutter:
  uses-material-design: true

  # Para agregar assets a tu aplicación, descomenta y usa esta sección:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Para agregar fuentes personalizadas, descomenta y usa esta sección:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700