name: amicana_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos y Fuentes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Manejo de Estado
  flutter_bloc: ^8.1.5
  provider: ^6.1.2 # (Puedes eliminar este o flutter_bloc si solo usarás uno)

  # Red y Peticiones HTTP
  http: ^1.2.1
  dio: ^5.4.3

  # Navegación
  go_router: ^14.1.0

  # Almacenamiento Local
  shared_preferences: ^2.2.3

  # Firebase (versiones actualizadas a junio de 2025)
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  flutterfire_cli: ^1.2.0 # <-- CORREGIDO: Se añadió el ^


# --- SECCIÓN ÚNICA Y CORRECTA DE FLUTTER ---
flutter:
  uses-material-design: true

  # Declaración de la carpeta de imágenes
  assets:
    - assets/images/

  # Para agregar fuentes personalizadas (ejemplo)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf