name: amicana_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos y Fuentes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Manejo de Estado
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  meta: ^1.12.0

  # Conectividad y Navegación
  go_router: ^14.1.0
  url_launcher: ^6.2.6
  dio: ^5.4.3 # <-- DEPENDENCIA AÑADIDA DE NUEVO

  # Almacenamiento Local
  shared_preferences: ^2.2.3

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/