// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXuiNzpSNqr_TGqPRCyvjyCs-YRmrWGmg',
    appId: '1:9356784355:web:408d6b96eae45e0005cbd6',
    messagingSenderId: '9356784355',
    projectId: 'amicana-8a036',
    authDomain: 'amicana-8a036.firebaseapp.com',
    storageBucket: 'amicana-8a036.firebasestorage.app',
    measurementId: 'G-9XQC4SPN4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8DBBJCf0We0yVBgthBtLrQ9KzIHCXlQM',
    appId: '1:9356784355:android:7bb390ac5d5b7cd805cbd6',
    messagingSenderId: '9356784355',
    projectId: 'amicana-8a036',
    storageBucket: 'amicana-8a036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBboUqA8aKUKPdqt2JFd7TDzuDQz-EpVUw',
    appId: '1:9356784355:ios:f4a21303b83100eb05cbd6',
    messagingSenderId: '9356784355',
    projectId: 'amicana-8a036',
    storageBucket: 'amicana-8a036.firebasestorage.app',
    androidClientId: '9356784355-44fjkqj6lbh1lt6bvoljauvsmbnoei1o.apps.googleusercontent.com',
    iosClientId: '9356784355-jk8cl6rrbp2reg0ps2isel35hlls9aja.apps.googleusercontent.com',
    iosBundleId: 'com.example.amicanaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBboUqA8aKUKPdqt2JFd7TDzuDQz-EpVUw',
    appId: '1:9356784355:ios:f4a21303b83100eb05cbd6',
    messagingSenderId: '9356784355',
    projectId: 'amicana-8a036',
    storageBucket: 'amicana-8a036.firebasestorage.app',
    androidClientId: '9356784355-44fjkqj6lbh1lt6bvoljauvsmbnoei1o.apps.googleusercontent.com',
    iosClientId: '9356784355-jk8cl6rrbp2reg0ps2isel35hlls9aja.apps.googleusercontent.com',
    iosBundleId: 'com.example.amicanaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXuiNzpSNqr_TGqPRCyvjyCs-YRmrWGmg',
    appId: '1:9356784355:web:68203a563aa5574105cbd6',
    messagingSenderId: '9356784355',
    projectId: 'amicana-8a036',
    authDomain: 'amicana-8a036.firebaseapp.com',
    storageBucket: 'amicana-8a036.firebasestorage.app',
    measurementId: 'G-BZ7JC56PWE',
  );

}